In [1]:
pip install openpyxl pandas

Requirement already satisfied: openpyxl in /home/jrr/.config/jupyterlab-desktop/jlab_server/lib/python3.12/site-packages (3.1.5)
Requirement already satisfied: pandas in /home/jrr/.config/jupyterlab-desktop/jlab_server/lib/python3.12/site-packages (2.2.2)
Requirement already satisfied: et-xmlfile in /home/jrr/.config/jupyterlab-desktop/jlab_server/lib/python3.12/site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: numpy>=1.26.0 in /home/jrr/.local/lib/python3.12/site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/jrr/.config/jupyterlab-desktop/jlab_server/lib/python3.12/site-packages (from pandas) (2.9.0)
Requirement already satisfied: pytz>=2020.1 in /home/jrr/.config/jupyterlab-desktop/jlab_server/lib/python3.12/site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /home/jrr/.config/jupyterlab-desktop/jlab_server/lib/python3.12/site-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in /home/jrr/.config/jupyterlab-desktop/jlab_server/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import numpy as np
import pandas as pd

# 🐼 Pandas

---

Imagine que você acabou de receber os resultados de um ensaio clínico com milhares de pacientes, ou os dados brutos de triagem milhares de dados. Tentar abrir, analisar e encontrar padrões nisso usando um software de planilha comum seria como tentar ler um livro onde todas as páginas foram embaralhadas. 

Na prática laboratorial, farmacêutica ou na ciência de dados em saúde, não lidamos com meias dúzias de linhas; lidamos com matrizes gigantescas que escondem informações cruciais para a tomada de decisão.

---

> 🤔 **Como podemos organizar, limpar e manipular essa verdadeira avalanche de dados sem perder semanas de trabalho fazendo isso manualmente?**

É justamente para resolver esse tipo de desafio que a ferramenta **Pandas** foi criada.

Em 2008, o desenvolvedor Wes McKinney trabalhava com dados financeiros complexos e precisava de uma solução mais robusta para análise e manipulação de informações. O nome *Pandas* não é uma homenagem ao urso, mas sim uma abreviação de **Panel Data (dados em painel)** e **Python Data Analysis**.

Na estatística e na economia, *dados em painel* referem-se à observação de múltiplos indivíduos acompanhados ao longo do tempo.

Na área da saúde e das ciências aplicadas, esse conceito também é conhecido como **estudo longitudinal** ou **coorte**.

---

## ⚙️ Os quatro superpoderes do Pandas

O Pandas foi desenvolvido para lidar com dados do mundo real e se apoia em quatro grandes capacidades:

### 🧹 Limpeza (Cleaning)

Permite identificar e tratar dados ausentes ou inconsistentes.
Exemplo: um paciente que não compareceu à coleta de sangue no Dia 15.

### 🔍 Exploração (Exploring)

Facilita a análise inicial dos dados, permitindo obter rapidamente medidas como média, valores máximos e variabilidade da amostra com poucos comandos.

### 🛠️ Manipulação (Manipulating)

Possibilita combinar diferentes bases de dados.
Exemplo: cruzar resultados de exames laboratoriais com registros de dispensação farmacêutica usando o ID do paciente.

### 📊 Análise (Analyzing)

Transforma dados brutos em conhecimento útil, permitindo gerar insights a partir das informações integradas.

# 📊 DataFrame

---

No dia a dia, ninguém analisa um único valor isolado. Nós trabalhamos com listas de pacientes, catálogos de medicamentos e planilhas lotadas de exames. Precisamos de uma estrutura prática para organizar tudo isso em formato de grade.

---

### O que é, afinal, um DataFrame?

De forma simples e direta: o **DataFrame** é a versão do Pandas para uma tabela comum.

Se você sabe o que é uma planilha do Excel/Sheets, você já entende o que é um DataFrame. Ele é uma estrutura bidimensional composta por:

* **Linhas (`Index`):** Representam as nossas *observações*. Cada linha é um Paciente, uma Amostra de Sangue ou uma Molécula diferente.
* **Colunas (`Columns`):** Representam as nossas *variáveis*. Cada coluna guarda uma informação, como a Idade, a Glicemia ou o Peso Molecular.

**Por que usar o DataFrame e não o Excel?**

Porque o DataFrame processa dados via código. Isso significa que ele não trava ao abrir milhões de linhas e permite que você filtre, limpe e faça cálculos estatísticos complexos em segundos.

In [3]:
# Aqui usamos o NumPy para gerar uma lista de números (idades)
# np.array cria um vetor numérico eficiente

idades = np.array([18, 22, 25, 30, 35])
# Também criamos outro vetor com notas (simulando um exame ou avaliação)
notas = [7.5, 8.0, 6.5, 9.0, 7.0]

animais = {
    "Animal": ["Cachorro", "Gato", "Elefante", "Leão", "Coelho"],
    "Habitat": ["Doméstico", "Doméstico", "Savana", "Savana", "Floresta"],
    "Expectativa_de_vida": [13, 15, 60, 14, 9],
    "Peso_medio_kg": [10, 4, 5400, 190, 2]
}

print("Idades dos alunos:", idades)
print("Resultados (notas):", notas)
print("Dicionario de animais:", animais)

Idades dos alunos: [18 22 25 30 35]
Resultados (notas): [7.5, 8.0, 6.5, 9.0, 7.0]
Dicionario de animais: {'Animal': ['Cachorro', 'Gato', 'Elefante', 'Leão', 'Coelho'], 'Habitat': ['Doméstico', 'Doméstico', 'Savana', 'Savana', 'Floresta'], 'Expectativa_de_vida': [13, 15, 60, 14, 9], 'Peso_medio_kg': [10, 4, 5400, 190, 2]}

In [4]:
# ================================
# 📊 Construindo a tabela
# ================================
# Aqui estamos pegando dados que já foram criados antes:
# - idades 
# - notas
# E organizando tudo em colunas nomeadas.

df = pd.DataFrame({
    "Idade": idades,  # coluna com as idades
    "Nota": notas     # coluna com as notas/resultados
})

df_animais = pd.DataFrame(animais)

In [5]:
# Agora imprimimos o DataFrame para ver como os dados ficaram organizados

print("📊 Tabela de dados (DataFrame):")
print(df)

📊 Tabela de dados (DataFrame):
   Idade  Nota
0     18   7.5
1     22   8.0
2     25   6.5
3     30   9.0
4     35   7.0

In [6]:

# Exibimos a tabela animais
print("\nTabela de Animais:")
print(df_animais)

Tabela de Animais:
     Animal    Habitat  Expectativa_de_vida  Peso_medio_kg
0  Cachorro  Doméstico                   13             10
1      Gato  Doméstico                   15              4
2  Elefante     Savana                   60           5400
3      Leão     Savana                   14            190
4    Coelho   Floresta                    9              2

O Pandas cria DataFrames a partir de diferentes estruturas: listas viram colunas simples quando passadas isoladamente; arrays NumPy são convertidos diretamente em colunas eficientes para cálculos; já dicionários são o formato mais natural, onde cada chave vira uma coluna e os valores viram as linhas. Isso facilita a organização e análise de dados em formato de tabela.

## 🚀 Como o Pandas transforma dados

### 📋 Lista → vira uma coluna quando agrupada em um DataFrame  
### ⚡ NumPy array → funciona como lista, mas otimizado para cálculos  
### 🗂️ Dicionário → já nasce estruturado em colunas (chave = coluna, valores = linhas)

👉 No final, o Pandas pega tudo isso e organiza em uma tabela chamada DataFrame.

# 📦 O que é uma Series no Pandas?

## 🧠 Definição simples

Uma **Series** no Pandas é uma estrutura de dados que representa uma **única coluna de dados**.

 ## **Acessando uma coluna específica do DataFrame**.

* `df` → é a tabela inteira (DataFrame)
* `["Idade"]` → seleciona **apenas a coluna chamada "Idade"**

In [7]:
df["Idade"]

0    18
1    22
2    25
3    30
4    35
Name: Idade, dtype: int64

In [8]:
df_animais["Habitat"]

0    Doméstico
1    Doméstico
2       Savana
3       Savana
4     Floresta
Name: Habitat, dtype: object

In [9]:
# ================================
# Média 
# ================================
media = idades.mean()

# ================================
# Desvio padrão
# ================================
desvio = idades.std()

print("📊 Média das idades:", media)
print("📉 Desvio padrão das idades:", desvio)

📊 Média das idades: 26.0
📉 Desvio padrão das idades: 5.966573556070519

In [10]:
# O método describe() gera um resumo estatístico automático
df["Idade"].describe()

count     5.000000
mean     26.000000
std       6.670832
min      18.000000
25%      22.000000
50%      25.000000
75%      30.000000
max      35.000000
Name: Idade, dtype: float64

In [11]:
df["Idade"].info()

<class 'pandas.core.series.Series'>
RangeIndex: 5 entries, 0 to 4
Series name: Idade
Non-Null Count  Dtype
--------------  -----
5 non-null      int64
dtypes: int64(1)
memory usage: 172.0 bytes

In [12]:
# O método describe() gera um resumo estatístico automático
# de todas as colunas numéricas do DataFrame.

# ================================
# 🧠 O que ele calcula?
# ================================
# Ele mostra rapidamente informações importantes como:
#
# - count → quantidade de valores (não nulos)
# - mean → média dos valores
# - std → desvio padrão (variação dos dados)
# - min → menor valor
# - 25% → primeiro quartil (25% dos dados abaixo desse valor)
# - 50% → mediana (valor central)
# - 75% → terceiro quartil (75% dos dados abaixo desse valor)
# - max → maior valor

df.describe()

           Idade      Nota
count   5.000000  5.000000
mean   26.000000  7.600000
std     6.670832  0.961769
min    18.000000  6.500000
25%    22.000000  7.000000
50%    25.000000  7.500000
75%    30.000000  8.000000
max    35.000000  9.000000

In [13]:
df_animais.describe()

       Expectativa_de_vida  Peso_medio_kg
count             5.000000       5.000000
mean             22.200000    1121.200000
std              21.253235    2393.259952
min               9.000000       2.000000
25%              13.000000       4.000000
50%              14.000000      10.000000
75%              15.000000     190.000000
max              60.000000    5400.000000

In [14]:
df_animais.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Animal               5 non-null      object
 1   Habitat              5 non-null      object
 2   Expectativa_de_vida  5 non-null      int64
 3   Peso_medio_kg        5 non-null      int64
dtypes: int64(2), object(2)
memory usage: 292.0+ bytes

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Idade   5 non-null      int64
 1   Nota    5 non-null      float64
dtypes: float64(1), int64(1)
memory usage: 212.0 bytes

### Na prática, quase nunca criamos DataFrames do zero.

👉 O mais comum é:
- receber arquivos prontos (Excel, CSV, banco de dados)
- carregar esses dados no Python
- e então fazer a análise

Ou seja:

> 📌 O trabalho real começa quando os dados já existem

## 📥 Métodos `read_*` do Pandas

Os métodos `read_*` servem para **ler arquivos/dados externos** e transformar tudo em um DataFrame.

```python
df = pd.read_csv("dados.csv")      # CSV
df = pd.read_excel("dados.xlsx")  # Excel
df = pd.read_json("dados.json")   # JSON/API
df = pd.read_sql("SELECT * FROM tabela", conexao)  # Banco de dados
````

🚀 Resumo :
```
📄 `read_csv()` → arquivos CSV
📊 `read_excel()` → planilhas Excel
🌐 `read_json()` → APIs e JSON
🗄️ `read_sql()` → bancos de dados
    
```

👉 Todos convertem dados externos em tabelas do Pandas (`DataFrame`).

In [16]:
#Para abrir um arquivo `.xlsx`, usamos:

df = pd.read_excel("../data/mock_dados.xlsx")

# Visualizando os dados
df

    ID      Nome  Idade          Cidade           Profissão  Salario
0    1       Ana     28       São Paulo   Analista de Dados     5200
1    2     Bruno     34        Campinas          Engenheiro     7800
2    3     Carla     22         Atibaia          Estagiária     1800
3    4    Daniel     45  Rio de Janeiro             Gerente    12000
4    5   Eduarda     30  Belo Horizonte           Biomédica     6400
5    6    Felipe     27        Curitiba       Desenvolvedor     7000
6    7  Gabriela     31    Porto Alegre  Cientista de Dados     9500
7    8  Henrique     39        Salvador         Coordenador     8800
8    9   Juliana     40        Campinas          Estagiário     9657
9   10    Thiago     42         Atibaia   Analista de Dados     6839
10  11    Rafael     44        Campinas          Estagiário    12262
11  12    Camila     25  Rio de Janeiro       Desenvolvedor    14089
12  13     Lucas     39        Curitiba       Desenvolvedor     7140
13  14   Larissa     33  Ribeirão Preto           Biomédica     2112
14  15   Juliana     48       São Paulo           Biomédica    12372
15  16     Pedro     49         Atibaia           Biomédica    14997
16  17     Pedro     32  Belo Horizonte             Gerente    14022
17  18    Camila     27  Rio de Janeiro   Analista de Dados     7047
18  19   Juliana     32  Rio de Janeiro          Estagiário    13983
19  20   Larissa     35        Campinas   Analista de Dados     9450
20  21  Patrícia     25  Rio de Janeiro          Engenheiro    12902
21  22   Juliana     20       São Paulo       Desenvolvedor    12090
22  23     Lucas     43  Ribeirão Preto          Engenheiro     9790
23  24      João     27        Sorocaba         UX Designer     4793
24  25      João     45        Sorocaba          Estagiário     4735
25  26      João     36  Belo Horizonte             Gerente    14710
26  27    Thiago     35         Atibaia   Analista de Dados    11787
27  28    Thiago     50         Atibaia  Cientista de Dados     6856
28  29   Larissa     45  Belo Horizonte  Cientista de Dados     7822
29  30    Thiago     49       São Paulo  Cientista de Dados    10333
30  31     Pedro     40  Rio de Janeiro           Biomédica     5671
31  32     Lucas     42        Curitiba             Gerente    14809
32  33     Pedro     20       São Paulo   Analista de Dados    12519
33  34    Thiago     47  Rio de Janeiro           Biomédica     2889
34  35   Mariana     39  Belo Horizonte         UX Designer    11491
35  36     Pedro     44       São Paulo       Desenvolvedor     4165
36  37  Patrícia     32        Sorocaba   Analista de Dados    10178
37  38   Juliana     47        Curitiba          Engenheiro     8184
38  39     Pedro     26        Sorocaba   Analista de Dados     5163
39  40   Larissa     53        Sorocaba       Desenvolvedor     5457
40  41    Thiago     30        Sorocaba             Gerente     9280
41  42     Lucas     55        Campinas       Desenvolvedor     9639
42  43     Pedro     34  Rio de Janeiro             Gerente     4873
43  44  Patrícia     52       São Paulo          Estagiário     9491
44  45   Mariana     26  Ribeirão Preto          Estagiário     8528
45  46    Rafael     54  Belo Horizonte          Estagiário     2189
46  47    Camila     37        Curitiba  Cientista de Dados     8494
47  48   Larissa     33  Belo Horizonte           Biomédica    14155
48  49    Camila     34        Campinas         UX Designer    13376
49  50     Lucas     26        Curitiba       Desenvolvedor     5786

```python
df.head()
df.tail()
```

## 🧠 O que são `head()` e `tail()` no Pandas?

Esses dois métodos servem para você **visualizar rapidamente o conteúdo de um DataFrame** sem precisar imprimir a tabela inteira.

---

## 📊 `df.head()` → primeiras linhas

* Mostra as **primeiras linhas do DataFrame**
* Por padrão, exibe **5 linhas**

```python
df.head()
```
---

## 📊 `df.tail()` → últimas linhas
* Mostra as **últimas linhas do DataFrame**
* Também mostra **5 linhas por padrão**

```python
df.tail()
```

In [17]:
df.head()

   ID     Nome  Idade          Cidade          Profissão  Salario
0   1      Ana     28       São Paulo  Analista de Dados     5200
1   2    Bruno     34        Campinas         Engenheiro     7800
2   3    Carla     22         Atibaia         Estagiária     1800
3   4   Daniel     45  Rio de Janeiro            Gerente    12000
4   5  Eduarda     30  Belo Horizonte          Biomédica     6400

In [18]:
df.tail()

    ID     Nome  Idade          Cidade           Profissão  Salario
45  46   Rafael     54  Belo Horizonte          Estagiário     2189
46  47   Camila     37        Curitiba  Cientista de Dados     8494
47  48  Larissa     33  Belo Horizonte           Biomédica    14155
48  49   Camila     34        Campinas         UX Designer    13376
49  50    Lucas     26        Curitiba       Desenvolvedor     5786

In [19]:
# Em ciência de dados, é muito comum criar novas informações a partir de dados já existentes.

# Aqui estamos criando uma nova coluna chamada "Salario_Anual"
# a partir da coluna "Salario"

df["Salario_Anual"] = df["Salario"] * 12
# Agora imprimimos o DataFrame atualizado com a nova coluna

print("\n📊 Dados com salário anual:")
df

📊 Dados com salário anual:

,ID,Nome,Idade,Cidade,Profissão,Salario,Salario_Anual
0,1,Ana,28,São Paulo,Analista de Dados,5200,62400
1,2,Bruno,34,Campinas,Engenheiro,7800,93600
2,3,Carla,22,Atibaia,Estagiária,1800,21600
3,4,Daniel,45,Rio de Janeiro,Gerente,12000,144000
4,5,Eduarda,30,Belo Horizonte,Biomédica,6400,76800
5,6,Felipe,27,Curitiba,Desenvolvedor,7000,84000
6,7,Gabriela,31,Porto Alegre,Cientista de Dados,9500,114000
7,8,Henrique,39,Salvador,Coordenador,8800,105600
8,9,Juliana,40,Campinas,Estagiário,9657,115884
9,10,Thiago,42,Atibaia,Analista de Dados,6839,82068
10,11,Rafael,44,Campinas,Estagiário,12262,147144
11,12,Camila,25,Rio de Janeiro,Desenvolvedor,14089,169068
12,13,Lucas,39,Curitiba,Desenvolvedor,7140,85680
13,14,Larissa,33,Ribeirão Preto,Biomédica,2112,25344
14,15,Juliana,48,São Paulo,Biomédica,12372,148464
15,16,Pedro,49,Atibaia,Biomédica,14997,179964
16,17,Pedro,32,Belo Horizonte,Gerente,14022,168264
17,18,Camila,27,Rio de Janeiro,Analista de Dados,7047,84564
18,19,Juliana,32,Rio de Janeiro,Estagiário,13983,167796
19,20,Larissa,35,Campinas,Analista de Dados,9450,113400
20,21,Patrícia,25,Rio de Janeiro,Engenheiro,12902,154824
21,22,Juliana,20,São Paulo,Desenvolvedor,12090,145080
22,23,Lucas,43,Ribeirão Preto,Engenheiro,9790,117480
23,24,João,27,Sorocaba,UX Designer,4793,57516
24,25,João,45,Sorocaba,Estagiário,4735,56820
25,26,João,36,Belo Horizonte,Gerente,14710,176520
26,27,Thiago,35,Atibaia,Analista de Dados,11787,141444
27,28,Thiago,50,Atibaia,Cientista de Dados,6856,82272
28,29,Larissa,45,Belo Horizonte,Cientista de Dados,7822,93864
29,30,Thiago,49,São Paulo,Cientista de Dados,10333,123996
30,31,Pedro,40,Rio de Janeiro,Biomédica,5671,68052
31,32,Lucas,42,Curitiba,Gerente,14809,177708
32,33,Pedro,20,São Paulo,Analista de Dados,12519,150228
33,34,Thiago,47,Rio de Janeiro,Biomédica,2889,34668
34,35,Mariana,39,Belo Horizonte,UX Designer,11491,137892
35,36,Pedro,44,São Paulo,Desenvolvedor,4165,49980
36,37,Patrícia,32,Sorocaba,Analista de Dados,10178,122136
37,38,Juliana,47,Curitiba,Engenheiro,8184,98208
38,39,Pedro,26,Sorocaba,Analista de Dados,5163,61956
39,40,Larissa,53,Sorocaba,Desenvolvedor,5457,65484
40,41,Thiago,30,Sorocaba,Gerente,9280,111360
41,42,Lucas,55,Campinas,Desenvolvedor,9639,115668
42,43,Pedro,34,Rio de Janeiro,Gerente,4873,58476
43,44,Patrícia,52,São Paulo,Estagiário,9491,113892
44,45,Mariana,26,Ribeirão Preto,Estagiário,8528,102336
45,46,Rafael,54,Belo Horizonte,Estagiário,2189,26268
46,47,Camila,37,Curitiba,Cientista de Dados,8494,101928
47,48,Larissa,33,Belo Horizonte,Biomédica,14155,169860
48,49,Camila,34,Campinas,UX Designer,13376,160512
49,50,Lucas,26,Curitiba,Desenvolvedor,5786,69432

# 🔎 Filtros no Pandas (seleção de dados)

Filtrar dados no Pandas significa **escolher apenas as linhas que atendem a uma condição**.

---

## 🧠 Ideia principal

Em vez de trabalhar com a tabela inteira, você pode perguntar:

> “quero apenas os registros que satisfazem essa regra”

---

## 📊 Exemplo básico

Vamos supor que temos um DataFrame `df` com uma coluna `Salario`.

In [20]:
# ================================
# 🔍 Filtro de dados
# ================================
filtro = df["Idade"] > 40
filtro

0     False
1     False
2     False
3      True
4     False
5     False
6     False
7     False
8     False
9      True
10     True
11    False
12    False
13    False
14     True
15     True
16    False
17    False
18    False
19    False
20    False
21    False
22     True
23    False
24     True
25    False
26    False
27     True
28     True
29     True
30    False
31     True
32    False
33     True
34    False
35     True
36    False
37     True
38    False
39     True
40    False
41     True
42    False
43     True
44    False
45     True
46    False
47    False
48    False
49    False
Name: Idade, dtype: bool

In [21]:
# ================================
# 🔍 Filtro de dados
# ================================
# Aqui estamos selecionando apenas as linhas
# onde a idade é maior que 40

df_filtrado = df[filtro]
df_filtrado

,ID,Nome,Idade,Cidade,Profissão,Salario,Salario_Anual
3,4,Daniel,45,Rio de Janeiro,Gerente,12000,144000
9,10,Thiago,42,Atibaia,Analista de Dados,6839,82068
10,11,Rafael,44,Campinas,Estagiário,12262,147144
14,15,Juliana,48,São Paulo,Biomédica,12372,148464
15,16,Pedro,49,Atibaia,Biomédica,14997,179964
22,23,Lucas,43,Ribeirão Preto,Engenheiro,9790,117480
24,25,João,45,Sorocaba,Estagiário,4735,56820
27,28,Thiago,50,Atibaia,Cientista de Dados,6856,82272
28,29,Larissa,45,Belo Horizonte,Cientista de Dados,7822,93864
29,30,Thiago,49,São Paulo,Cientista de Dados,10333,123996
31,32,Lucas,42,Curitiba,Gerente,14809,177708
33,34,Thiago,47,Rio de Janeiro,Biomédica,2889,34668
35,36,Pedro,44,São Paulo,Desenvolvedor,4165,49980
37,38,Juliana,47,Curitiba,Engenheiro,8184,98208
39,40,Larissa,53,Sorocaba,Desenvolvedor,5457,65484
41,42,Lucas,55,Campinas,Desenvolvedor,9639,115668
43,44,Patrícia,52,São Paulo,Estagiário,9491,113892
45,46,Rafael,54,Belo Horizonte,Estagiário,2189,26268

In [22]:
df_animais

     Animal    Habitat  Expectativa_de_vida  Peso_medio_kg
0  Cachorro  Doméstico                   13             10
1      Gato  Doméstico                   15              4
2  Elefante     Savana                   60           5400
3      Leão     Savana                   14            190
4    Coelho   Floresta                    9              2

In [23]:
# ================================
# 🐾 Filtrar animais da Savana
# ================================

savana = df_animais[df_animais["Habitat"] == "Savana"]

print("\n🦁 Animais da Savana:")
print(savana)

🦁 Animais da Savana:
     Animal Habitat  Expectativa_de_vida  Peso_medio_kg
2  Elefante  Savana                   60           5400
3      Leão  Savana                   14            190

In [24]:
# ================================
# ⚖️ Filtrar animais com peso maior que 200kg
# ================================

pesados = df_animais[df_animais["Peso_medio_kg"] > 200]

print("\n🐘 Animais com mais de 200kg:")
print(pesados)

🐘 Animais com mais de 200kg:
     Animal Habitat  Expectativa_de_vida  Peso_medio_kg
2  Elefante  Savana                   60           5400

In [25]:
# Aqui estamos combinando as duas condições ao mesmo tempo

# O símbolo "&" significa:
# 👉 "E" (AND lógico)

filtro_idade = df["Idade"] > 40
filtro_salario = df["Salario"] > 1621

df[filtro_idade & filtro_salario]

,ID,Nome,Idade,Cidade,Profissão,Salario,Salario_Anual
3,4,Daniel,45,Rio de Janeiro,Gerente,12000,144000
9,10,Thiago,42,Atibaia,Analista de Dados,6839,82068
10,11,Rafael,44,Campinas,Estagiário,12262,147144
14,15,Juliana,48,São Paulo,Biomédica,12372,148464
15,16,Pedro,49,Atibaia,Biomédica,14997,179964
22,23,Lucas,43,Ribeirão Preto,Engenheiro,9790,117480
24,25,João,45,Sorocaba,Estagiário,4735,56820
27,28,Thiago,50,Atibaia,Cientista de Dados,6856,82272
28,29,Larissa,45,Belo Horizonte,Cientista de Dados,7822,93864
29,30,Thiago,49,São Paulo,Cientista de Dados,10333,123996
31,32,Lucas,42,Curitiba,Gerente,14809,177708
33,34,Thiago,47,Rio de Janeiro,Biomédica,2889,34668
35,36,Pedro,44,São Paulo,Desenvolvedor,4165,49980
37,38,Juliana,47,Curitiba,Engenheiro,8184,98208
39,40,Larissa,53,Sorocaba,Desenvolvedor,5457,65484
41,42,Lucas,55,Campinas,Desenvolvedor,9639,115668
43,44,Patrícia,52,São Paulo,Estagiário,9491,113892
45,46,Rafael,54,Belo Horizonte,Estagiário,2189,26268

# 🧼 Valores Nulos no Pandas

Em ciência de dados, é muito comum encontrar **dados faltando** em uma tabela.  
Esses valores ausentes precisam ser identificados e tratados antes da análise.

---

## ❌ O que é NaN?

- `NaN` significa **"Not a Number"**
- Representa um **dado faltante ou não registrado**
- Pode aparecer por:
  - falha na coleta de dados
  - campos não preenchidos
  - erro de importação de arquivos

---

In [26]:
# ================================
# 📂 Lendo um arquivo Excel
# ================================
# Aqui estamos carregando um arquivo pronto (.xlsx)
# Esse arquivo pode conter dados incompletos (valores faltando)
df_nulos =  pd.read_excel("../data/mock_dados_valores_nulos.xlsx")

In [27]:
#`isna()` → identificar valores faltantes
#A função `isna()` verifica onde existem valores ausentes.
df_nulos.isna()

       ID   Nome  Idade  Cidade  Profissão  Salario  Ativo
0    True  False  False   False      False    False  False
1   False  False  False   False      False    False  False
2   False  False   True   False      False    False  False
3   False  False  False    True      False    False  False
4   False  False  False   False       True     True  False
5   False  False  False   False       True    False  False
6   False  False  False   False       True    False  False
7   False  False  False   False       True    False  False
8   False  False  False   False       True    False  False
9   False  False  False   False       True    False  False
10   True  False  False   False      False    False  False
11  False  False   True   False      False    False  False
12  False  False  False    True      False    False  False
13  False  False  False   False       True    False  False
14  False  False  False   False      False     True  False
15  False  False  False   False      False    False  False
16  False  False  False   False       True    False  False
17  False  False  False   False      False    False  False
18  False  False  False   False      False    False  False
19  False  False  False   False      False    False  False
20  False  False  False    True      False    False  False
21  False  False  False    True      False    False  False
22  False  False  False   False      False    False  False
23  False  False  False   False      False    False  False
24  False  False  False   False      False    False  False
25  False  False  False   False      False    False  False
26  False  False  False   False      False    False  False
27  False  False  False   False      False    False  False
28  False  False  False   False      False    False  False
29  False  False  False   False      False    False  False
30  False  False  False   False      False    False  False
31  False  False   True    True       True    False  False
32  False  False   True    True       True    False  False
33  False  False   True    True       True    False  False
34  False  False  False   False      False     True  False
35  False  False  False   False      False     True  False
36  False  False  False   False      False     True  False
37  False  False  False   False      False     True  False
38  False  False  False   False      False     True  False
39  False  False  False   False      False     True  False
40  False  False  False   False      False     True  False
41  False  False  False   False      False     True  False
42  False  False  False   False      False     True  False
43  False  False   True    True      False     True  False
44  False  False   True    True      False     True  False
45  False  False   True    True      False     True  False
46  False  False   True    True      False     True  False
47  False  False  False   False      False     True  False
48  False  False  False   False      False     True  False
49  False  False  False   False      False     True  False

In [28]:
#Podemos combinar com sum() para saber quantos valores faltam em cada coluna:
# mostra a quantidade de NaN por coluna
df_nulos.isna().sum()

ID            2
Nome          0
Idade         9
Cidade       11
Profissão    11
Salario      18
Ativo         0
dtype: int64

In [29]:
# ================================
# 🧹 dropna() -> remove valores nulos
# ================================

# Remove linhas com valores nulos
df_drop = df_nulos.dropna()

# Remove linhas onde "Salario" está vazio
df_salario = df_nulos.dropna(subset=["Salario"])

# Remove colunas que possuem valores nulos
df_colunas = df_nulos.dropna(axis=1)
 
# ================================
# 📊 Exibindo resultados
# ================================

print("\n🧹 Linhas sem valores nulos:")
print(df_drop)

print("\n💰 Linhas com salário preenchido:")
print(df_salario)


print("\n📋 Colunas sem valores nulos:")
print(df_colunas)

🧹 Linhas sem valores nulos:
      ID     Nome  Idade          Cidade           Profissão  Salario  Ativo
1    2.0      Ana   34.0        Campinas          Engenheiro   7800.0  False
15  16.0    Pedro   49.0         Atibaia           Biomédica  14997.0   True
17  18.0   Camila   27.0  Rio de Janeiro   Analista de Dados   7047.0  False
18  19.0  Juliana   32.0  Rio de Janeiro          Estagiário  13983.0   True
19  20.0  Larissa   35.0        Campinas   Analista de Dados   9450.0  False
22  23.0    Lucas   43.0  Ribeirão Preto          Engenheiro   9790.0   True
23  24.0     João   27.0        Sorocaba         UX Designer   4793.0   True
24  25.0     João   45.0        Sorocaba          Estagiário   4735.0   True
25  26.0     João   36.0  Belo Horizonte             Gerente  14710.0  False
26  27.0   Thiago   35.0         Atibaia   Analista de Dados  11787.0   True
27  28.0   Thiago   50.0         Atibaia  Cientista de Dados   6856.0  False
28  29.0    Pedro   45.0  Belo Horizonte  Cientista de Dados   7822.0   True
29  30.0    Pedro   49.0       São Paulo  Cientista de Dados  10333.0  False
30  31.0    Pedro   40.0  Rio de Janeiro           Biomédica   5671.0   True

💰 Linhas com salário preenchido:
      ID      Nome  Idade          Cidade           Profissão  Salario  Ativo
0    NaN       Ana   28.0       São Paulo   Analista de Dados   5200.0   True
1    2.0       Ana   34.0        Campinas          Engenheiro   7800.0  False
2    3.0     Carla    NaN         Atibaia          Estagiária   1800.0   True
3    4.0    Daniel   45.0             NaN             Gerente  12000.0  False
5    6.0    Felipe   27.0        Curitiba                 NaN   7000.0  False
6    7.0  Gabriela   31.0    Porto Alegre                 NaN   9500.0   True
7    8.0  Henrique   39.0        Salvador                 NaN   8800.0   True
8    9.0   Juliana   40.0        Campinas                 NaN   9657.0   True
9   10.0    Thiago   42.0         Atibaia                 NaN   6839.0  False
10   NaN    Rafael   44.0        Campinas          Estagiário  12262.0   True
11  12.0    Rafael    NaN  Rio de Janeiro       Desenvolvedor  14089.0  False
12  13.0     Lucas   39.0             NaN       Desenvolvedor   7140.0   True
13  14.0   Larissa   33.0  Ribeirão Preto                 NaN   2112.0  False
15  16.0     Pedro   49.0         Atibaia           Biomédica  14997.0   True
16  17.0     Pedro   32.0  Belo Horizonte                 NaN  14022.0   True
17  18.0    Camila   27.0  Rio de Janeiro   Analista de Dados   7047.0  False
18  19.0   Juliana   32.0  Rio de Janeiro          Estagiário  13983.0   True
19  20.0   Larissa   35.0        Campinas   Analista de Dados   9450.0  False
20  21.0  Patrícia   25.0             NaN          Engenheiro  12902.0   True
21  22.0   Juliana   20.0             NaN       Desenvolvedor  12090.0  False
22  23.0     Lucas   43.0  Ribeirão Preto          Engenheiro   9790.0   True
23  24.0      João   27.0        Sorocaba         UX Designer   4793.0   True
24  25.0      João   45.0        Sorocaba          Estagiário   4735.0   True
25  26.0      João   36.0  Belo Horizonte             Gerente  14710.0  False
26  27.0    Thiago   35.0         Atibaia   Analista de Dados  11787.0   True
27  28.0    Thiago   50.0         Atibaia  Cientista de Dados   6856.0  False
28  29.0     Pedro   45.0  Belo Horizonte  Cientista de Dados   7822.0   True
29  30.0     Pedro   49.0       São Paulo  Cientista de Dados  10333.0  False
30  31.0     Pedro   40.0  Rio de Janeiro           Biomédica   5671.0   True
31  32.0     Lucas    NaN             NaN                 NaN  14809.0   True
32  33.0     Pedro    NaN             NaN                 NaN  12519.0   True
33  34.0    Thiago    NaN             NaN                 NaN   2889.0  False

📋 Colunas sem valores nulos:
        Nome  Ativo
0        Ana   True
1        Ana  False
2      Carla   True
3     Daniel  False
4    Eduarda   True
5     Felipe  False
6   Gabriela   True
7   Henrique   True
8    Juliana   True
9     Thiago  False
10    Rafael   True
11    Rafael  False
12     Lucas   True
13   Larissa  False
14   Juliana   True
15     Pedro   True
16     Pedro   True
17    Camila  False
18   Juliana   True
19   Larissa  False
20  Patrícia   True
21   Juliana  False
22     Lucas   True
23      João   True
24      João   True
25      João  False
26    Thiago   True
27    Thiago  False
28     Pedro   True
29     Pedro  False
30     Pedro   True
31     Lucas   True
32     Pedro   True
33    Thiago  False
34   Mariana   True
35     Pedro  False
36  Patrícia   True
37   Juliana  False
38     Pedro   True
39   Larissa   True
40    Thiago   True
41     Lucas  False
42     Pedro   True
43   Juliana  False
44     Pedro   True
45   Larissa  False
46   Juliana   True
47   Larissa   True
48    Camila   True
49     Lucas  False

In [30]:
# ================================
# 🔧 Preenchendo valores nulos
# ================================
# Substitui valores faltantes por um valor escolhido

df_preenchido = df_nulos.fillna({
    "Idade": df["Idade"].mean(),
    "Cidade": "Desconhecido",
    "Profissão": "Não informado",
    "Salario": df["Salario"].median()
})

print(df_preenchido)

      ID      Nome  Idade          Cidade           Profissão  Salario  Ativo
0    NaN       Ana  28.00       São Paulo   Analista de Dados   5200.0   True
1    2.0       Ana  34.00        Campinas          Engenheiro   7800.0  False
2    3.0     Carla  36.96         Atibaia          Estagiária   1800.0   True
3    4.0    Daniel  45.00    Desconhecido             Gerente  12000.0  False
4    5.0   Eduarda  30.00  Belo Horizonte       Não informado   9040.0   True
5    6.0    Felipe  27.00        Curitiba       Não informado   7000.0  False
6    7.0  Gabriela  31.00    Porto Alegre       Não informado   9500.0   True
7    8.0  Henrique  39.00        Salvador       Não informado   8800.0   True
8    9.0   Juliana  40.00        Campinas       Não informado   9657.0   True
9   10.0    Thiago  42.00         Atibaia       Não informado   6839.0  False
10   NaN    Rafael  44.00        Campinas          Estagiário  12262.0   True
11  12.0    Rafael  36.96  Rio de Janeiro       Desenvolvedor  14089.0  False
12  13.0     Lucas  39.00    Desconhecido       Desenvolvedor   7140.0   True
13  14.0   Larissa  33.00  Ribeirão Preto       Não informado   2112.0  False
14  15.0   Juliana  48.00       São Paulo           Biomédica   9040.0   True
15  16.0     Pedro  49.00         Atibaia           Biomédica  14997.0   True
16  17.0     Pedro  32.00  Belo Horizonte       Não informado  14022.0   True
17  18.0    Camila  27.00  Rio de Janeiro   Analista de Dados   7047.0  False
18  19.0   Juliana  32.00  Rio de Janeiro          Estagiário  13983.0   True
19  20.0   Larissa  35.00        Campinas   Analista de Dados   9450.0  False
20  21.0  Patrícia  25.00    Desconhecido          Engenheiro  12902.0   True
21  22.0   Juliana  20.00    Desconhecido       Desenvolvedor  12090.0  False
22  23.0     Lucas  43.00  Ribeirão Preto          Engenheiro   9790.0   True
23  24.0      João  27.00        Sorocaba         UX Designer   4793.0   True
24  25.0      João  45.00        Sorocaba          Estagiário   4735.0   True
25  26.0      João  36.00  Belo Horizonte             Gerente  14710.0  False
26  27.0    Thiago  35.00         Atibaia   Analista de Dados  11787.0   True
27  28.0    Thiago  50.00         Atibaia  Cientista de Dados   6856.0  False
28  29.0     Pedro  45.00  Belo Horizonte  Cientista de Dados   7822.0   True
29  30.0     Pedro  49.00       São Paulo  Cientista de Dados  10333.0  False
30  31.0     Pedro  40.00  Rio de Janeiro           Biomédica   5671.0   True
31  32.0     Lucas  36.96    Desconhecido       Não informado  14809.0   True
32  33.0     Pedro  36.96    Desconhecido       Não informado  12519.0   True
33  34.0    Thiago  36.96    Desconhecido       Não informado   2889.0  False
34  35.0   Mariana  39.00  Belo Horizonte         UX Designer   9040.0   True
35  36.0     Pedro  44.00       São Paulo       Desenvolvedor   9040.0  False
36  37.0  Patrícia  32.00        Sorocaba   Analista de Dados   9040.0   True
37  38.0   Juliana  47.00        Curitiba          Engenheiro   9040.0  False
38  39.0     Pedro  26.00        Sorocaba   Analista de Dados   9040.0   True
39  40.0   Larissa  53.00        Sorocaba       Desenvolvedor   9040.0   True
40  41.0    Thiago  30.00        Sorocaba             Gerente   9040.0   True
41  42.0     Lucas  55.00        Campinas       Desenvolvedor   9040.0  False
42  43.0     Pedro  34.00  Rio de Janeiro             Gerente   9040.0   True
43  44.0   Juliana  36.96    Desconhecido          Estagiário   9040.0  False
44  45.0     Pedro  36.96    Desconhecido          Estagiário   9040.0   True
45  46.0   Larissa  36.96    Desconhecido          Estagiário   9040.0  False
46  47.0   Juliana  36.96    Desconhecido  Cientista de Dados   9040.0   True
47  48.0   Larissa  33.00  Belo Horizonte           Biomédica   9040.0   True
48  49.0    Camila  34.00        Campinas         UX Designer   9040.0   True
49  50.0     Lucas  26.00        Curitiba       Desenvolvedor   9040.0  False

In [31]:
# ================================
# 🔄 astype() -> converte tipos de dados
# ================================

# Verificando os tipos atuais
print(df_nulos.dtypes)

ID           float64
Nome          object
Idade        float64
Cidade        object
Profissão     object
Salario      float64
Ativo           bool
dtype: object

In [32]:
# Convertendo a coluna Idade para inteiro

df_preenchido["Idade"] = df_preenchido["Idade"].astype(int)

# Convertendo salário para float
df_preenchido["Salario"] = df_preenchido["Salario"].astype(float)

# Convertendo Nome para texto/string
df_preenchido["Nome"] = df_preenchido["Nome"].astype(str)


# ================================
# 📊 Verificando tipos das colunas
# ================================

print("📌 Tipo da coluna 'Idade' antes do astype():")
print(df_nulos["Idade"].dtype)

print("\n🔄 Tipo da coluna 'Idade' depois do astype(int):")
print(df_preenchido["Idade"].dtype)

print("\n📋 DataFrame final:")
print(df_preenchido)

📌 Tipo da coluna 'Idade' antes do astype():
float64

🔄 Tipo da coluna 'Idade' depois do astype(int):
int64

📋 DataFrame final:
      ID      Nome  Idade          Cidade           Profissão  Salario  Ativo
0    NaN       Ana     28       São Paulo   Analista de Dados   5200.0   True
1    2.0       Ana     34        Campinas          Engenheiro   7800.0  False
2    3.0     Carla     36         Atibaia          Estagiária   1800.0   True
3    4.0    Daniel     45    Desconhecido             Gerente  12000.0  False
4    5.0   Eduarda     30  Belo Horizonte       Não informado   9040.0   True
5    6.0    Felipe     27        Curitiba       Não informado   7000.0  False
6    7.0  Gabriela     31    Porto Alegre       Não informado   9500.0   True
7    8.0  Henrique     39        Salvador       Não informado   8800.0   True
8    9.0   Juliana     40        Campinas       Não informado   9657.0   True
9   10.0    Thiago     42         Atibaia       Não informado   6839.0  False
10   NaN    Rafael     44        Campinas          Estagiário  12262.0   True
11  12.0    Rafael     36  Rio de Janeiro       Desenvolvedor  14089.0  False
12  13.0     Lucas     39    Desconhecido       Desenvolvedor   7140.0   True
13  14.0   Larissa     33  Ribeirão Preto       Não informado   2112.0  False
14  15.0   Juliana     48       São Paulo           Biomédica   9040.0   True
15  16.0     Pedro     49         Atibaia           Biomédica  14997.0   True
16  17.0     Pedro     32  Belo Horizonte       Não informado  14022.0   True
17  18.0    Camila     27  Rio de Janeiro   Analista de Dados   7047.0  False
18  19.0   Juliana     32  Rio de Janeiro          Estagiário  13983.0   True
19  20.0   Larissa     35        Campinas   Analista de Dados   9450.0  False
20  21.0  Patrícia     25    Desconhecido          Engenheiro  12902.0   True
21  22.0   Juliana     20    Desconhecido       Desenvolvedor  12090.0  False
22  23.0     Lucas     43  Ribeirão Preto          Engenheiro   9790.0   True
23  24.0      João     27        Sorocaba         UX Designer   4793.0   True
24  25.0      João     45        Sorocaba          Estagiário   4735.0   True
25  26.0      João     36  Belo Horizonte             Gerente  14710.0  False
26  27.0    Thiago     35         Atibaia   Analista de Dados  11787.0   True
27  28.0    Thiago     50         Atibaia  Cientista de Dados   6856.0  False
28  29.0     Pedro     45  Belo Horizonte  Cientista de Dados   7822.0   True
29  30.0     Pedro     49       São Paulo  Cientista de Dados  10333.0  False
30  31.0     Pedro     40  Rio de Janeiro           Biomédica   5671.0   True
31  32.0     Lucas     36    Desconhecido       Não informado  14809.0   True
32  33.0     Pedro     36    Desconhecido       Não informado  12519.0   True
33  34.0    Thiago     36    Desconhecido       Não informado   2889.0  False
34  35.0   Mariana     39  Belo Horizonte         UX Designer   9040.0   True
35  36.0     Pedro     44       São Paulo       Desenvolvedor   9040.0  False
36  37.0  Patrícia     32        Sorocaba   Analista de Dados   9040.0   True
37  38.0   Juliana     47        Curitiba          Engenheiro   9040.0  False
38  39.0     Pedro     26        Sorocaba   Analista de Dados   9040.0   True
39  40.0   Larissa     53        Sorocaba       Desenvolvedor   9040.0   True
40  41.0    Thiago     30        Sorocaba             Gerente   9040.0   True
41  42.0     Lucas     55        Campinas       Desenvolvedor   9040.0  False
42  43.0     Pedro     34  Rio de Janeiro             Gerente   9040.0   True
43  44.0   Juliana     36    Desconhecido          Estagiário   9040.0  False
44  45.0     Pedro     36    Desconhecido          Estagiário   9040.0   True
45  46.0   Larissa     36    Desconhecido          Estagiário   9040.0  False
46  47.0   Juliana     36    Desconhecido  Cientista de Dados   9040.0   True
47  48.0   Larissa     33  Belo Horizonte           Biomédica   9040.0   True
48  49.0    Camila     34        Campinas         UX Designer   9040.0   True
49  50.0     Lucas     26        Curitiba       Desenvolvedor   9040.0  False

## 🔄 Ordenação no Pandas: `sort_values()`

O método `sort_values()` é usado para **ordenar linhas** de um DataFrame com base em uma ou mais colunas.

---

## ⚡ Parâmetros mais usados

| Parâmetro | Função |
|---|---|
| `by` | coluna usada na ordenação |
| `ascending=True` | crescente |
| `ascending=False` | decrescente |
| `inplace=True` | altera o DataFrame original |

In [33]:
# 📌 Sintaxe básica

df.sort_values(by="Idade")

,ID,Nome,Idade,Cidade,Profissão,Salario,Salario_Anual
21,22,Juliana,20,São Paulo,Desenvolvedor,12090,145080
32,33,Pedro,20,São Paulo,Analista de Dados,12519,150228
2,3,Carla,22,Atibaia,Estagiária,1800,21600
20,21,Patrícia,25,Rio de Janeiro,Engenheiro,12902,154824
11,12,Camila,25,Rio de Janeiro,Desenvolvedor,14089,169068
49,50,Lucas,26,Curitiba,Desenvolvedor,5786,69432
38,39,Pedro,26,Sorocaba,Analista de Dados,5163,61956
44,45,Mariana,26,Ribeirão Preto,Estagiário,8528,102336
23,24,João,27,Sorocaba,UX Designer,4793,57516
17,18,Camila,27,Rio de Janeiro,Analista de Dados,7047,84564
5,6,Felipe,27,Curitiba,Desenvolvedor,7000,84000
0,1,Ana,28,São Paulo,Analista de Dados,5200,62400
4,5,Eduarda,30,Belo Horizonte,Biomédica,6400,76800
40,41,Thiago,30,Sorocaba,Gerente,9280,111360
6,7,Gabriela,31,Porto Alegre,Cientista de Dados,9500,114000
18,19,Juliana,32,Rio de Janeiro,Estagiário,13983,167796
36,37,Patrícia,32,Sorocaba,Analista de Dados,10178,122136
16,17,Pedro,32,Belo Horizonte,Gerente,14022,168264
13,14,Larissa,33,Ribeirão Preto,Biomédica,2112,25344
47,48,Larissa,33,Belo Horizonte,Biomédica,14155,169860
42,43,Pedro,34,Rio de Janeiro,Gerente,4873,58476
1,2,Bruno,34,Campinas,Engenheiro,7800,93600
48,49,Camila,34,Campinas,UX Designer,13376,160512
26,27,Thiago,35,Atibaia,Analista de Dados,11787,141444
19,20,Larissa,35,Campinas,Analista de Dados,9450,113400
25,26,João,36,Belo Horizonte,Gerente,14710,176520
46,47,Camila,37,Curitiba,Cientista de Dados,8494,101928
12,13,Lucas,39,Curitiba,Desenvolvedor,7140,85680
7,8,Henrique,39,Salvador,Coordenador,8800,105600
34,35,Mariana,39,Belo Horizonte,UX Designer,11491,137892
8,9,Juliana,40,Campinas,Estagiário,9657,115884
30,31,Pedro,40,Rio de Janeiro,Biomédica,5671,68052
9,10,Thiago,42,Atibaia,Analista de Dados,6839,82068
31,32,Lucas,42,Curitiba,Gerente,14809,177708
22,23,Lucas,43,Ribeirão Preto,Engenheiro,9790,117480
35,36,Pedro,44,São Paulo,Desenvolvedor,4165,49980
10,11,Rafael,44,Campinas,Estagiário,12262,147144
24,25,João,45,Sorocaba,Estagiário,4735,56820
28,29,Larissa,45,Belo Horizonte,Cientista de Dados,7822,93864
3,4,Daniel,45,Rio de Janeiro,Gerente,12000,144000
33,34,Thiago,47,Rio de Janeiro,Biomédica,2889,34668
37,38,Juliana,47,Curitiba,Engenheiro,8184,98208
14,15,Juliana,48,São Paulo,Biomédica,12372,148464
15,16,Pedro,49,Atibaia,Biomédica,14997,179964
29,30,Thiago,49,São Paulo,Cientista de Dados,10333,123996
27,28,Thiago,50,Atibaia,Cientista de Dados,6856,82272
43,44,Patrícia,52,São Paulo,Estagiário,9491,113892
39,40,Larissa,53,Sorocaba,Desenvolvedor,5457,65484
45,46,Rafael,54,Belo Horizonte,Estagiário,2189,26268
41,42,Lucas,55,Campinas,Desenvolvedor,9639,115668

In [34]:
# 🔽 Ordem decrescente
df.sort_values(by="Salario", ascending=False)

,ID,Nome,Idade,Cidade,Profissão,Salario,Salario_Anual
15,16,Pedro,49,Atibaia,Biomédica,14997,179964
31,32,Lucas,42,Curitiba,Gerente,14809,177708
25,26,João,36,Belo Horizonte,Gerente,14710,176520
47,48,Larissa,33,Belo Horizonte,Biomédica,14155,169860
11,12,Camila,25,Rio de Janeiro,Desenvolvedor,14089,169068
16,17,Pedro,32,Belo Horizonte,Gerente,14022,168264
18,19,Juliana,32,Rio de Janeiro,Estagiário,13983,167796
48,49,Camila,34,Campinas,UX Designer,13376,160512
20,21,Patrícia,25,Rio de Janeiro,Engenheiro,12902,154824
32,33,Pedro,20,São Paulo,Analista de Dados,12519,150228
14,15,Juliana,48,São Paulo,Biomédica,12372,148464
10,11,Rafael,44,Campinas,Estagiário,12262,147144
21,22,Juliana,20,São Paulo,Desenvolvedor,12090,145080
3,4,Daniel,45,Rio de Janeiro,Gerente,12000,144000
26,27,Thiago,35,Atibaia,Analista de Dados,11787,141444
34,35,Mariana,39,Belo Horizonte,UX Designer,11491,137892
29,30,Thiago,49,São Paulo,Cientista de Dados,10333,123996
36,37,Patrícia,32,Sorocaba,Analista de Dados,10178,122136
22,23,Lucas,43,Ribeirão Preto,Engenheiro,9790,117480
8,9,Juliana,40,Campinas,Estagiário,9657,115884
41,42,Lucas,55,Campinas,Desenvolvedor,9639,115668
6,7,Gabriela,31,Porto Alegre,Cientista de Dados,9500,114000
43,44,Patrícia,52,São Paulo,Estagiário,9491,113892
19,20,Larissa,35,Campinas,Analista de Dados,9450,113400
40,41,Thiago,30,Sorocaba,Gerente,9280,111360
7,8,Henrique,39,Salvador,Coordenador,8800,105600
44,45,Mariana,26,Ribeirão Preto,Estagiário,8528,102336
46,47,Camila,37,Curitiba,Cientista de Dados,8494,101928
37,38,Juliana,47,Curitiba,Engenheiro,8184,98208
28,29,Larissa,45,Belo Horizonte,Cientista de Dados,7822,93864
1,2,Bruno,34,Campinas,Engenheiro,7800,93600
12,13,Lucas,39,Curitiba,Desenvolvedor,7140,85680
17,18,Camila,27,Rio de Janeiro,Analista de Dados,7047,84564
5,6,Felipe,27,Curitiba,Desenvolvedor,7000,84000
27,28,Thiago,50,Atibaia,Cientista de Dados,6856,82272
9,10,Thiago,42,Atibaia,Analista de Dados,6839,82068
4,5,Eduarda,30,Belo Horizonte,Biomédica,6400,76800
49,50,Lucas,26,Curitiba,Desenvolvedor,5786,69432
30,31,Pedro,40,Rio de Janeiro,Biomédica,5671,68052
39,40,Larissa,53,Sorocaba,Desenvolvedor,5457,65484
0,1,Ana,28,São Paulo,Analista de Dados,5200,62400
38,39,Pedro,26,Sorocaba,Analista de Dados,5163,61956
42,43,Pedro,34,Rio de Janeiro,Gerente,4873,58476
23,24,João,27,Sorocaba,UX Designer,4793,57516
24,25,João,45,Sorocaba,Estagiário,4735,56820
35,36,Pedro,44,São Paulo,Desenvolvedor,4165,49980
33,34,Thiago,47,Rio de Janeiro,Biomédica,2889,34668
45,46,Rafael,54,Belo Horizonte,Estagiário,2189,26268
13,14,Larissa,33,Ribeirão Preto,Biomédica,2112,25344
2,3,Carla,22,Atibaia,Estagiária,1800,21600

In [35]:
# 🧩 Ordenando por mais de uma coluna
df.sort_values(by=["Cidade", "Salario"])

,ID,Nome,Idade,Cidade,Profissão,Salario,Salario_Anual
2,3,Carla,22,Atibaia,Estagiária,1800,21600
9,10,Thiago,42,Atibaia,Analista de Dados,6839,82068
27,28,Thiago,50,Atibaia,Cientista de Dados,6856,82272
26,27,Thiago,35,Atibaia,Analista de Dados,11787,141444
15,16,Pedro,49,Atibaia,Biomédica,14997,179964
45,46,Rafael,54,Belo Horizonte,Estagiário,2189,26268
4,5,Eduarda,30,Belo Horizonte,Biomédica,6400,76800
28,29,Larissa,45,Belo Horizonte,Cientista de Dados,7822,93864
34,35,Mariana,39,Belo Horizonte,UX Designer,11491,137892
16,17,Pedro,32,Belo Horizonte,Gerente,14022,168264
47,48,Larissa,33,Belo Horizonte,Biomédica,14155,169860
25,26,João,36,Belo Horizonte,Gerente,14710,176520
1,2,Bruno,34,Campinas,Engenheiro,7800,93600
19,20,Larissa,35,Campinas,Analista de Dados,9450,113400
41,42,Lucas,55,Campinas,Desenvolvedor,9639,115668
8,9,Juliana,40,Campinas,Estagiário,9657,115884
10,11,Rafael,44,Campinas,Estagiário,12262,147144
48,49,Camila,34,Campinas,UX Designer,13376,160512
49,50,Lucas,26,Curitiba,Desenvolvedor,5786,69432
5,6,Felipe,27,Curitiba,Desenvolvedor,7000,84000
12,13,Lucas,39,Curitiba,Desenvolvedor,7140,85680
37,38,Juliana,47,Curitiba,Engenheiro,8184,98208
46,47,Camila,37,Curitiba,Cientista de Dados,8494,101928
31,32,Lucas,42,Curitiba,Gerente,14809,177708
6,7,Gabriela,31,Porto Alegre,Cientista de Dados,9500,114000
13,14,Larissa,33,Ribeirão Preto,Biomédica,2112,25344
44,45,Mariana,26,Ribeirão Preto,Estagiário,8528,102336
22,23,Lucas,43,Ribeirão Preto,Engenheiro,9790,117480
33,34,Thiago,47,Rio de Janeiro,Biomédica,2889,34668
42,43,Pedro,34,Rio de Janeiro,Gerente,4873,58476
30,31,Pedro,40,Rio de Janeiro,Biomédica,5671,68052
17,18,Camila,27,Rio de Janeiro,Analista de Dados,7047,84564
3,4,Daniel,45,Rio de Janeiro,Gerente,12000,144000
20,21,Patrícia,25,Rio de Janeiro,Engenheiro,12902,154824
18,19,Juliana,32,Rio de Janeiro,Estagiário,13983,167796
11,12,Camila,25,Rio de Janeiro,Desenvolvedor,14089,169068
7,8,Henrique,39,Salvador,Coordenador,8800,105600
24,25,João,45,Sorocaba,Estagiário,4735,56820
23,24,João,27,Sorocaba,UX Designer,4793,57516
38,39,Pedro,26,Sorocaba,Analista de Dados,5163,61956
39,40,Larissa,53,Sorocaba,Desenvolvedor,5457,65484
40,41,Thiago,30,Sorocaba,Gerente,9280,111360
36,37,Patrícia,32,Sorocaba,Analista de Dados,10178,122136
35,36,Pedro,44,São Paulo,Desenvolvedor,4165,49980
0,1,Ana,28,São Paulo,Analista de Dados,5200,62400
43,44,Patrícia,52,São Paulo,Estagiário,9491,113892
29,30,Thiago,49,São Paulo,Cientista de Dados,10333,123996
21,22,Juliana,20,São Paulo,Desenvolvedor,12090,145080
14,15,Juliana,48,São Paulo,Biomédica,12372,148464
32,33,Pedro,20,São Paulo,Analista de Dados,12519,150228

## 📌 Diferença entre `sort_values()` e `sort_index()`

| Método | O que ordena |
|---|---|
| `sort_values()` | valores das colunas |
| `sort_index()` | índices/linhas |

---

## 🚀 Resumo mental rápido

📊 `sort_values()` → ordena pelos valores da coluna  
🔽 `ascending=False` → maior para menor  
🧩 `by=[]` → múltiplas colunas  
🛠️ `inplace=True` → altera o DataFrame original

In [36]:
dados = {
    "Nome": ["Ana", "Carlos", "Bruno"],
    "Idade": [23, 35, 19]
}

df = pd.DataFrame(dados, index=[2, 0, 1])

print("📋 DataFrame original:")
print(df)

print("\n🔢 Índice ordenado:")
print(df.sort_index())

📋 DataFrame original:
     Nome  Idade
2     Ana     23
0  Carlos     35
1   Bruno     19

🔢 Índice ordenado:
     Nome  Idade
0  Carlos     35
1   Bruno     19
2     Ana     23

## 📊 `value_counts()` no Pandas

O método `value_counts()` conta quantas vezes cada valor aparece em uma coluna.

In [37]:
# Conta quantas vezes cada cidade aparece
contagem_cidades = df_nulos["Cidade"].value_counts()

print("📍 Quantidade de pessoas por cidade:")
print(contagem_cidades)

📍 Quantidade de pessoas por cidade:
Cidade
Campinas          6
Belo Horizonte    6
Sorocaba          6
Rio de Janeiro    5
Atibaia           5
São Paulo         4
Curitiba          3
Ribeirão Preto    2
Porto Alegre      1
Salvador          1
Name: count, dtype: int64

In [38]:
# Mostra a proporção/percentual de cada valor
# Em vez da quantidade absoluta

percentual_cidades = df_nulos["Cidade"].value_counts(normalize=True).round(3)

print("\n📊 Percentual por cidade:")
print(percentual_cidades)

📊 Percentual por cidade:
Cidade
Campinas          0.154
Belo Horizonte    0.154
Sorocaba          0.154
Rio de Janeiro    0.128
Atibaia           0.128
São Paulo         0.103
Curitiba          0.077
Ribeirão Preto    0.051
Porto Alegre      0.026
Salvador          0.026
Name: proportion, dtype: float64

In [39]:
# ================================
# 🔍 dropna=False
# ================================

# Também conta valores nulos (NaN)

contagem_nulos = df_nulos["Cidade"].value_counts(dropna=False)

print("\n🧹 Contando valores nulos:")
print(contagem_nulos)

🧹 Contando valores nulos:
Cidade
NaN               11
Belo Horizonte     6
Campinas           6
Sorocaba           6
Atibaia            5
Rio de Janeiro     5
São Paulo          4
Curitiba           3
Ribeirão Preto     2
Porto Alegre       1
Salvador           1
Name: count, dtype: int64

# 📊 Agregações com `groupby()` no Pandas

O método `groupby()` serve para **agrupar dados** por uma coluna e depois aplicar cálculos (média, soma, contagem, etc).

👉 Muito usado para análises e relatórios.

---

## 🧠 Estrutura mental do `groupby()`

```python
df.groupby("COLUNA")[["COLUNA_NUMERICA"]].METODO()
```

---
## 🔧 Métodos de agregação mais usados

| Método    | Função      |
| --------- | ----------- |
| `mean()`  | Média       |
| `sum()`   | Soma        |
| `count()` | Contagem    |
| `max()`   | Maior valor |
| `min()`   | Menor valor |

---

### 👉 Uma forma MUITO mais fácil de entender `groupby()` é ler o código **de trás pra frente**.

---

## 📌 Exemplo

```python
df.groupby("Cidade")["Salario"].mean()
```

### 🔄 Leitura natural:

```python
mean()
```

👉 calcular a média

↓

```python
["Salario"]
```

👉 da coluna salário

↓

```python
groupby("Cidade")
```

👉 agrupando por cidade

In [40]:
# ================================
# 📊 MÉDIA SALARIAL POR CIDADE
# ================================

# 1. Agrupa os dados pela coluna "Cidade"
# 2. Seleciona a coluna "Salario"
# 3. Calcula a média dos salários

media_salario = df_preenchido.groupby("Cidade")["Salario"].mean().round(2)

print("📊 Média salarial por cidade:")
print(media_salario)

📊 Média salarial por cidade:
Cidade
Atibaia            8455.80
Belo Horizonte    10612.33
Campinas           9541.50
Curitiba           8360.00
Desconhecido      10046.27
Porto Alegre       9500.00
Ribeirão Preto     5951.00
Rio de Janeiro     9966.00
Salvador           8800.00
Sorocaba           7614.67
São Paulo          8403.25
Name: Salario, dtype: float64

In [41]:
# ================================
# 🔢 QUANTIDADE DE PESSOAS POR PROFISSÃO
# ================================

# Conta quantos nomes existem em cada profissão

contagem_profissao = df_preenchido.groupby("Profissão")["Nome"].count()

print("\n👨‍💼 Quantidade de pessoas por profissão:")
print(contagem_profissao)

👨‍💼 Quantidade de pessoas por profissão:
Profissão
Analista de Dados      6
Biomédica              4
Cientista de Dados     4
Desenvolvedor          7
Engenheiro             4
Estagiária             1
Estagiário             6
Gerente                4
Não informado         11
UX Designer            3
Name: Nome, dtype: int64

In [42]:
# ================================
# 💰 SOMA DOS SALÁRIOS POR CIDADE
# ================================

# Soma todos os salários de cada cidade

soma_salarios = df_preenchido.groupby("Cidade")["Salario"].sum()

print("\n💰 Soma dos salários por cidade:")
print(soma_salarios)

💰 Soma dos salários por cidade:
Cidade
Atibaia            42279.0
Belo Horizonte     63674.0
Campinas           57249.0
Curitiba           25080.0
Desconhecido      110509.0
Porto Alegre        9500.0
Ribeirão Preto     11902.0
Rio de Janeiro     49830.0
Salvador            8800.0
Sorocaba           45688.0
São Paulo          33613.0
Name: Salario, dtype: float64

In [43]:
# ================================
# MAIOR IDADE POR CIDADE
# ================================

# Mostra a maior idade encontrada em cada cidade

maior_idade = df_preenchido.groupby("Cidade")["Idade"].max()

print("\n Maior idade por cidade:")
print(maior_idade)

 Maior idade por cidade:
Cidade
Atibaia           50
Belo Horizonte    45
Campinas          55
Curitiba          47
Desconhecido      45
Porto Alegre      31
Ribeirão Preto    43
Rio de Janeiro    40
Salvador          39
Sorocaba          53
São Paulo         49
Name: Idade, dtype: int64

In [44]:
# ⬇️ MENOR SALÁRIO POR PROFISSÃO
# ================================

# Mostra o menor salário de cada profissão

menor_salario = df_preenchido.groupby("Profissão")["Salario"].min()

print("\n Menor salário por profissão:")
print(menor_salario)

 Menor salário por profissão:
Profissão
Analista de Dados     5200.0
Biomédica             5671.0
Cientista de Dados    6856.0
Desenvolvedor         7140.0
Engenheiro            7800.0
Estagiária            1800.0
Estagiário            4735.0
Gerente               9040.0
Não informado         2112.0
UX Designer           4793.0
Name: Salario, dtype: float64

# 📚 Agrupando por mais de uma coluna no `groupby()`

No Pandas, podemos passar uma **lista de colunas** dentro do `groupby()`.

👉 Isso cria grupos mais específicos.

---

## 📌 Estrutura

```python
df.groupby(["COLUNA_1", "COLUNA_2"])["COLUNA_NUMERICA"].METODO()

In [45]:
# ================================
# 📊 AGRUPANDO POR CIDADE E PROFISSÃO
# ================================

# O groupby() vai criar grupos usando:
# 1. Cidade
# 2. Profissão
#
# Depois:
# - selecionamos a coluna "Salario"
# - calculamos a média salarial de cada grupo

media_salario = df_preenchido.groupby(["Cidade", "Profissão"])["Salario"].mean().round(2)

print("📊 Média salarial por cidade e profissão:")
print(media_salario)

📊 Média salarial por cidade e profissão:
Cidade          Profissão
Atibaia         Analista de Dados     11787.00
                Biomédica             14997.00
                Cientista de Dados     6856.00
                Estagiária             1800.00
                Não informado          6839.00
Belo Horizonte  Biomédica              9040.00
                Cientista de Dados     7822.00
                Gerente               14710.00
                Não informado         11531.00
                UX Designer            9040.00
Campinas        Analista de Dados      9450.00
                Desenvolvedor          9040.00
                Engenheiro             7800.00
                Estagiário            12262.00
                Não informado          9657.00
                UX Designer            9040.00
Curitiba        Desenvolvedor          9040.00
                Engenheiro             9040.00
                Não informado          7000.00
Desconhecido    Cientista de Dados     9040.00
                Desenvolvedor          9615.00
                Engenheiro            12902.00
                Estagiário             9040.00
                Gerente               12000.00
                Não informado         10072.33
Porto Alegre    Não informado          9500.00
Ribeirão Preto  Engenheiro             9790.00
                Não informado          2112.00
Rio de Janeiro  Analista de Dados      7047.00
                Biomédica              5671.00
                Desenvolvedor         14089.00
                Estagiário            13983.00
                Gerente                9040.00
Salvador        Não informado          8800.00
Sorocaba        Analista de Dados      9040.00
                Desenvolvedor          9040.00
                Estagiário             4735.00
                Gerente                9040.00
                UX Designer            4793.00
São Paulo       Analista de Dados      5200.00
                Biomédica              9040.00
                Cientista de Dados    10333.00
                Desenvolvedor          9040.00
Name: Salario, dtype: float64

In [51]:
# ================================
# 👥 CONTANDO PESSOAS POR CIDADE E STATUS
# ================================

# Agrupa por:
# - Nome
# - Cidade
# - Ativo
#
# Depois agrupa ela media das idades

contagem = df_preenchido.groupby(["Nome", "Cidade", "Ativo"])["Idade"].mean().round(2)

print("\n👥 Quantidade de pessoas por cidade e ativo:")
print(contagem)

👥 Quantidade de pessoas por cidade e ativo:
Nome      Cidade          Ativo
Ana       Campinas        False    34.0
          São Paulo       True     28.0
Camila    Campinas        True     34.0
          Rio de Janeiro  False    27.0
Carla     Atibaia         True     36.0
Daniel    Desconhecido    False    45.0
Eduarda   Belo Horizonte  True     30.0
Felipe    Curitiba        False    27.0
Gabriela  Porto Alegre    True     31.0
Henrique  Salvador        True     39.0
João      Belo Horizonte  False    36.0
          Sorocaba        True     36.0
Juliana   Campinas        True     40.0
          Curitiba        False    47.0
          Desconhecido    False    28.0
                          True     36.0
          Rio de Janeiro  True     32.0
          São Paulo       True     48.0
Larissa   Belo Horizonte  True     33.0
          Campinas        False    35.0
          Desconhecido    False    36.0
          Ribeirão Preto  False    33.0
          Sorocaba        True     53.0
Lucas     Campinas        False    55.0
          Curitiba        False    26.0
          Desconhecido    True     37.5
          Ribeirão Preto  True     43.0
Mariana   Belo Horizonte  True     39.0
Patrícia  Desconhecido    True     25.0
          Sorocaba        True     32.0
Pedro     Atibaia         True     49.0
          Belo Horizonte  True     38.5
          Desconhecido    True     36.0
          Rio de Janeiro  True     37.0
          Sorocaba        True     26.0
          São Paulo       False    46.5
Rafael    Campinas        True     44.0
          Rio de Janeiro  False    36.0
Thiago    Atibaia         False    46.0
                          True     35.0
          Desconhecido    False    36.0
          Sorocaba        True     30.0
Name: Idade, dtype: float64

# 📊 `.agg()` no Pandas

O método `.agg()` permite aplicar **várias agregações ao mesmo tempo**.

👉 Em vez de fazer apenas média OU soma, podemos fazer tudo junto.

---

# 📌 Estrutura

```python
df.groupby("COLUNA")["COLUNA_NUMERICA"].agg(["mean", "max", "min"])
```

---

In [54]:
# ================================
# 📊 MÚLTIPLAS AGREGAÇÕES
# ================================

# Agrupa os dados pela coluna "Cidade"
# Depois calcula:
# - média
# - maior valor
# - menor valor

estatisticas = df_preenchido.groupby(
    "Cidade"
)["Salario"].agg([
    "mean",
    "max",
    "min"
])

print("📊 Estatísticas salariais por cidade:")
print(estatisticas)

📊 Estatísticas salariais por cidade:
                        mean      max     min
Cidade
Atibaia          8455.800000  14997.0  1800.0
Belo Horizonte  10612.333333  14710.0  7822.0
Campinas         9541.500000  12262.0  7800.0
Curitiba         8360.000000   9040.0  7000.0
Desconhecido    10046.272727  14809.0  2889.0
Porto Alegre     9500.000000   9500.0  9500.0
Ribeirão Preto   5951.000000   9790.0  2112.0
Rio de Janeiro   9966.000000  14089.0  5671.0
Salvador         8800.000000   8800.0  8800.0
Sorocaba         7614.666667   9040.0  4735.0
São Paulo        8403.250000  10333.0  5200.0

In [56]:
estat_cidade = df_preenchido.groupby("Cidade").agg({
    "Salario": ["mean", "max"],
    "Idade": ["min", "max"]
})

print("📊 Estatísticas por cidade:")
estat_cidade

📊 Estatísticas por cidade:

                     Salario          Idade
                        mean      max   min max
Cidade
Atibaia          8455.800000  14997.0    35  50
Belo Horizonte  10612.333333  14710.0    30  45
Campinas         9541.500000  12262.0    34  55
Curitiba         8360.000000   9040.0    26  47
Desconhecido    10046.272727  14809.0    20  45
Porto Alegre     9500.000000   9500.0    31  31
Ribeirão Preto   5951.000000   9790.0    33  43
Rio de Janeiro   9966.000000  14089.0    27  40
Salvador         8800.000000   8800.0    39  39
Sorocaba         7614.666667   9040.0    26  53
São Paulo        8403.250000  10333.0    28  49